// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_eTmLCEFStEMugU20tQF73FiGv4qwytk',
    appId: '1:901267600129:web:54dbf0c32589b8b29e6100',
    messagingSenderId: '901267600129',
    projectId: 'thiagopt',
    authDomain: 'thiagopt.firebaseapp.com',
    storageBucket: 'thiagopt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHsN0Xb57R0DpqQzRFuf0iT3FA8aw5tY',
    appId: '1:901267600129:android:f0339f228e7604459e6100',
    messagingSenderId: '901267600129',
    projectId: 'thiagopt',
    storageBucket: 'thiagopt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc2eTLOrCa4k_mvUaCmUPgxqlj2T7wTek',
    appId: '1:901267600129:ios:25adc4c9e4357b3d9e6100',
    messagingSenderId: '901267600129',
    projectId: 'thiagopt',
    storageBucket: 'thiagopt.firebasestorage.app',
    iosBundleId: 'com.example.bioMatch',
  );
}
