name: bio_match
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  http: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_maps_flutter: ^2.12.0
  dio: ^5.8.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/trash.png
    - assets/images/hands.png
  fonts:
    - family: DoppioOne
      fonts:
        - asset: assets/fonts/DoppioOne-Regular.ttf

        
    